// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tasker/data/models/category_model.dart';
import 'package:tasker/data/models/recurrence_model.dart';
import 'package:tasker/data/models/tag_model.dart';
import 'package:tasker/data/models/task_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(RecurrenceModelAdapter());
    registerAdapter(TagModelAdapter());
    registerAdapter(TaskModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(RecurrenceModelAdapter());
    registerAdapter(TagModelAdapter());
    registerAdapter(TaskModelAdapter());
  }
}
